package astgen

import (
	"fmt"
	"strings"

	"github.com/scjalliance/astconf/astorg"
	"github.com/scjalliance/astconf/astval"
	"github.com/scjalliance/astconf/pjsip"
)

// authName returns the name of the pjsip auth section for a device.
func authName(username string) string {
	return username + "-auth"
}

// aorName returns the name of the pjsip aor section for a device.
func aorName(username string) string {
	return username + "-aor"
}

// Endpoints generates PJSIP endpoint entries for a dataset.
//
// The values in the base configuration will be merged into each endpoint
// that is returned.
//
// Each endpoint references an auth section and an aor section named
// after the endpoint. Those sections are generated by Auths and AORs.
func Endpoints(data *astorg.DataSet, base pjsip.Endpoint, context string) []pjsip.Endpoint {
	lookup := data.Lookup()

	// Progressively add endpoints to an ordered map
	var m pjsip.EndpointMap

	// Step 1: Add all phones
	for _, phone := range data.Phones {
		username := lineUsername(phone.MAC, lookup)
		if username == "" {
			continue
		}
		var vars []astval.Var
		var callerID string
		if phone.Location != "" {
			vars = append(vars, astval.NewVar("USER_LOCATION", phone.Location))
			if loc, ok := lookup.LocationByName[phone.Location]; ok {
				vars = append(vars, astval.NewVar("OUTBOUND_CALLERID", loc.CallerID))
				vars = append(vars, astval.NewVar("AREACODE", loc.AreaCode))
				if loc.Abbreviation != "" {
					callerID = fmt.Sprintf("\"%s-%s\" <UNAVAILABLE>", loc.Abbreviation, strings.ToUpper(phone.MAC))
				}
			}
		}
		endpoint := pjsip.Endpoint{
			Name:      username,
			Templates: phone.Templates,
			Auth:      authName(username),
			AORs:      []string{aorName(username)},
			CallerID:  callerID,
			Variables: vars,
		}
		m.Add(pjsip.MergeEndpoints(base, endpoint))
	}

	// Step 2: Add all software phones
	for _, phone := range data.Softphones {
		var vars []astval.Var
		var callerID string
		if phone.Location != "" {
			vars = append(vars, astval.NewVar("USER_LOCATION", phone.Location))
			if loc, ok := lookup.LocationByName[phone.Location]; ok {
				vars = append(vars, astval.NewVar("OUTBOUND_CALLERID", loc.CallerID))
				vars = append(vars, astval.NewVar("AREACODE", loc.AreaCode))
				if loc.Abbreviation != "" {
					callerID = fmt.Sprintf("\"%s-%s\" <UNAVAILABLE>", loc.Abbreviation, phone.Username)
				}
			}
		}
		endpoint := pjsip.Endpoint{
			Name:      phone.Username,
			Templates: phone.Templates,
			Auth:      authName(phone.Username),
			AORs:      []string{aorName(phone.Username)},
			CallerID:  callerID,
			Variables: vars,
		}
		m.Add(pjsip.MergeEndpoints(base, endpoint))
	}

	// Step 3: Merge person configuration
	var (
		phoneComplete     = make(map[string]bool) // Keep track of which phones are fully configured
		softphoneComplete = make(map[string]bool) // Keep track of which software phones are fully configured
	)

	for _, person := range data.People {
		var vars []astval.Var
		if person.VoicemailCode != "" {
			vars = append(vars, astval.NewVar("VMCODE", person.VoicemailCode))
		}
		for _, number := range person.ContactNumbers {
			if strings.Contains(strings.ToLower(number.Label), "mobile") {
				vars = append(vars, astval.NewVar("MOBILE", number.Dial))
				break
			}
		}
		vars = append(vars, astval.NewVar("USERNAME", person.Username))
		for _, mac := range person.Phones {
			username := lineUsername(mac, lookup)
			if !m.Contains(username) || phoneComplete[mac] {
				continue
			}
			endpoint := pjsip.Endpoint{
				Name:      username,
				CallerID:  fmt.Sprintf("\"%s\" <%s>", person.FullName, person.Extension),
				Mailboxes: []string{fmt.Sprintf("%s@%s", person.Extension, context)},
				Variables: vars,
			}
			m.Merge(endpoint)
			phoneComplete[mac] = true
		}
		for _, username := range person.Softphones {
			if !m.Contains(username) || softphoneComplete[username] {
				continue
			}
			endpoint := pjsip.Endpoint{
				Name:      username,
				CallerID:  fmt.Sprintf("\"%s\" <%s>", person.FullName, person.Extension),
				Variables: vars,
			}
			m.Merge(endpoint)
			softphoneComplete[username] = true
		}
	}

	// Step 4: Merge phone role configuration
	for _, role := range data.PhoneRoles {
		for _, mac := range role.Phones {
			username := lineUsername(mac, lookup)
			if !m.Contains(username) || phoneComplete[mac] {
				continue
			}
			endpoint := pjsip.Endpoint{
				Name:     username,
				CallerID: fmt.Sprintf("\"%s\" <%s>", role.DisplayName, role.Extension),
			}
			if role.MailboxNumber != "" {
				endpoint.Mailboxes = []string{fmt.Sprintf("%s@%s", role.MailboxNumber, context)}
			}
			m.Merge(endpoint)
			phoneComplete[mac] = true
		}
		for _, username := range role.Softphones {
			if !m.Contains(username) || softphoneComplete[username] {
				continue
			}
			endpoint := pjsip.Endpoint{
				Name:     username,
				CallerID: fmt.Sprintf("\"%s\" <%s>", role.DisplayName, role.Extension),
			}
			m.Merge(endpoint)
			softphoneComplete[username] = true
		}
	}

	// Return the compiled set of endpoint entries
	return m.Endpoints()
}

// Auths generates PJSIP auth entries for a dataset, one for each phone and
// software phone.
//
// The values in the base configuration will be overlayed by each auth
// that is returned.
func Auths(data *astorg.DataSet, base pjsip.Auth) []pjsip.Auth {
	lookup := data.Lookup()

	// Progressively add auths to an ordered map
	var m pjsip.AuthMap

	// Step 1: Add all phones
	for _, phone := range data.Phones {
		username := lineUsername(phone.MAC, lookup)
		if username == "" {
			continue
		}
		auth := pjsip.Auth{
			Name:     authName(username),
			Username: username,
			Password: phone.Secret,
		}
		m.Add(pjsip.OverlayAuths(base, auth))
	}

	// Step 2: Add all software phones
	for _, phone := range data.Softphones {
		auth := pjsip.Auth{
			Name:     authName(phone.Username),
			Username: phone.Username,
			Password: phone.Secret,
		}
		m.Add(pjsip.OverlayAuths(base, auth))
	}

	// Return the compiled set of auth entries
	return m.Auths()
}

// AORs generates PJSIP aor entries for a dataset, one for each phone and
// software phone.
//
// The values in the base configuration will be merged into each aor
// that is returned.
func AORs(data *astorg.DataSet, base pjsip.AOR) []pjsip.AOR {
	lookup := data.Lookup()

	// Progressively add aors to an ordered map
	var m pjsip.AORMap

	// Step 1: Add all phones
	for _, phone := range data.Phones {
		username := lineUsername(phone.MAC, lookup)
		if username == "" {
			continue
		}
		aor := pjsip.AOR{
			Name: aorName(username),
		}
		m.Add(pjsip.MergeAORs(base, aor))
	}

	// Step 2: Add all software phones
	for _, phone := range data.Softphones {
		aor := pjsip.AOR{
			Name: aorName(phone.Username),
		}
		m.Add(pjsip.MergeAORs(base, aor))
	}

	// Return the compiled set of aor entries
	return m.AORs()
}
